---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/3/8 20:50
---
local ComponentTurnStrategy = class("ComponentTurnStrategy", ComponentBase)
local ComponentDefine = require("Engine/Systems/ObjectSystem/Components/ComponentDefine")
local SkillConfigData = require("MainGame/ConfigData/SkillConfigData")
local Time = Time
ComponentTurnStrategy.m_ComponentId = ComponentDefine.ComponentType.k_ComponentSkillTarget

function ComponentTurnStrategy:Init(object)
    ComponentTurnStrategy.__super.Init(self, object)

end

function ComponentTurnStrategy:SetFormationPositionXYZ(positionX, positionY, positionZ)
    self.m_FormationPositionX = positionX
    self.m_FormationPositionY = positionY
    self.m_FormationPositionZ = positionZ
end

function ComponentTurnStrategy:SetFormationPosition(position)
    self.m_FormationPositionX = position.x
    self.m_FormationPositionY = position.y
    self.m_FormationPositionZ = position.z
end

function ComponentTurnStrategy:GetFormationPositionXYZ()
    return self.m_FormationPositionX, self.m_FormationPositionY, self.m_FormationPositionZ
end

return ComponentTurnStrategy