---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/12/24 17:11
---
local ComponentDefine = require("Engine/Systems/ObjectSystem/Components/ComponentDefine")
local ComponentPlaySpeedControl = class("ComponentPlaySpeedControl", ComponentBase)
ComponentPlaySpeedControl.m_ComponentId = ComponentDefine.ComponentType.k_ComponentPlaySpeedControl

function ComponentPlaySpeedControl:Init(object)
    ComponentPlaySpeedControl.__super.Init(self, object)
    self.m_AttachSprites = {}
    self.m_Speed = 1
end

function ComponentPlaySpeedControl:SetSpeed(speed, needSetAttachObject)
    if speed == self.m_Speed then
        return
    end
    self.m_Speed = speed
    self.m_Owner:SetAnimationPlaySpeed(speed)
    local effectComponent = self.m_EffectComponent
    if effectComponent then
        effectComponent:SetSpeed(speed)
    end

    if needSetAttachObject == true then
        for i, v in ipairs(self.m_AttachSprites) do
            v.m_PlaySpeedControlComponent:SetSpeed(speed, false)
        end
    end
end

function ComponentPlaySpeedControl:Attach(object)
    if self.m_Owner.m_PlaySpeedControlActive then
        table.insert(self.m_AttachSprites, object)
    end
end

function ComponentPlaySpeedControl:DetachOtherObjects()
    self.m_AttachSprites = {}
end

return ComponentPlaySpeedControl