---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/11/4 10:32
---
local ComponentDefine = require("Engine/Systems/ObjectSystem/Components/ComponentDefine")
local ComponentQuest = class("ComponentQuest", ComponentBase)
ComponentQuest.m_ComponentId = ComponentDefine.ComponentType.k_ComponentQuest

function ComponentQuest:Init(object)
    ComponentQuest.__super.Init(self, object)
end

function ComponentQuest:Deserialize(netBuffer)
    --- main
    self:DeserializeSingleQuest(netBuffer)
    --- side
    local side_quest_cnt = netBuffer:ReadInt()
    for i = 1, side_quest_cnt do
        self:DeserializeSingleQuest(netBuffer)
    end

    --- finished
    local finished_cnt = netBuffer:ReadInt()
    for i = 1, finished_cnt do
        local finished_id = netBuffer:ReadInt()
    end
end

function ComponentQuest:DeserializeSingleQuest(netBuffer)
    local quest_id_ = netBuffer:ReadInt()
    local cursor_ = netBuffer:ReadInt()
    local length = netBuffer:ReadInt()
    for i = 1, length do
        local target_id_ = netBuffer:ReadInt()
        local finished_ = netBuffer:ReadInt()
    end

    local prized_ = netBuffer:ReadUByte()
end

return ComponentQuest