---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/9/16 10:27
---

local DamageTypeDefine = {
    k_Circle = 1,
    k_Rect = 2,
    k_Sector = 3,
}

return DamageTypeDefine