---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/8/2 11:20
---
 
CoreCallbackManager = CoreCallbackManager or {}
local Core_LuaCallbackManager = SGEngine.Core.LuaCallbackManager

--子类重新写
local function OnSkillEvent(objectID, eventName)
    local object = ObjectManager.GetObject(objectID)
    if not object then
        Logger.Error("[CoreCallbackManager](OnSkillEvent) None object, ID:%s", objectID)
        return
    end
    StateSkill.OnSkillEvent(object, eventName)
end

local function OnSkillStart(objectID, skillId)
    local object = ObjectManager.GetObject(objectID)
    if not object then
        Logger.Error("[CoreCallbackManager](OnSkillStart) None object, ID:%s", objectID)
        return
    end
    StateSkill.OnSkillStart(object, skillId)
end

local function OnSkillEnd(objectID, skillId)
    local object = ObjectManager.GetObject(objectID)
    if not object then
        Logger.Error("[CoreCallbackManager](OnSkillEnd) None object, ID:%s", objectID)
        return
    end
    StateSkill.OnSkillEnd(object, skillId)
end

local function OnSkillMove(objectID)
    local object = ObjectManager.GetObject(objectID)
    if not object then
        Logger.Error("[CoreCallbackManager](OnSkillMove) None object, ID:%s", objectID)
        return
    end
    StateSkill.OnSkillMove(object)
end

local function OnSkillMoveStop(objectID)
    local object = ObjectManager.GetObject(objectID)
    if not object then
        Logger.Error("[CoreCallbackManager](OnSkillMoveStop) None object, ID:%s", objectID)
        return
    end
    StateSkill.OnSkillMoveStop(object)
end

local function OnCoreFootPrintCallback(objectID, bodyPart, intParam)
    local object = ObjectManager.GetObject(objectID)
    if not object then
        Logger.Error("[CoreCallbackManager](OnCoreFootPrintCallback) None object, ID:%s", objectID)
        return
    end
    if not object.m_FootprintComponent then
        return
    end
    object.m_FootprintComponent:OnFootPrintCallback(bodyPart, intParam)
end

local function OnStateStageCallback(objectID, stateDefine, stateMsg)
    local object = ObjectManager.GetObject(objectID)
    if not object then
        Logger.Error("[CoreCallbackManager](OnStateStageCallback) None object, ID:%s", objectID)
        return
    end

    if not object.m_StateComponent then
        return
    end
    object.m_StateComponent:Dispatch(stateDefine, stateMsg)
end

local function OnBeginMoveLuaCallBack(objectID)
    local object = ObjectManager.GetObject(objectID)
    if not object then
        Logger.Error("[CoreCallbackManager](OnBeginMoveLuaCallBack) None object, ID:%s", objectID)
        return
    end
    if not object.m_StateComponent then
        return
    end
    object.m_StateComponent:OnBeginMove()
end

local function OnStopMoveLuaCallBack(objectID)
    local object = ObjectManager.GetObject(objectID)
    if not object then
        Logger.Error("[CoreCallbackManager](OnStopMoveLuaCallBack) None object, ID:%s", objectID)
        return
    end
    if not object.m_StateComponent then
        return
    end
    object.m_StateComponent:OnStopMove()
end

function CoreCallbackManager.Init()
    local manager = Core_LuaCallbackManager.Instance
    manager:RegSkillEventCallback(OnSkillEvent)
    manager:RegSkillStartCallback(OnSkillStart)
    manager:RegSkillEndCallback(OnSkillEnd)
    manager:RegSkillBeginMoveCallback(OnSkillMove)
    manager:RegSkillMoveStopCallback(OnSkillMoveStop)
    manager:RegFootprintCallback(OnCoreFootPrintCallback)
    manager:RegStateStageCallback(OnStateStageCallback)
    manager:RegOnBeginMoveLuaCallBack(OnBeginMoveLuaCallBack)
    manager:RegOnStopMoveLuaCallBack(OnStopMoveLuaCallBack)
end

function CoreCallbackManager.Destroy()
    local manager = Core_LuaCallbackManager.Instance
    manager:UnRegSkillEventCallback()
    manager:UnRegSkillStartCallback()
    manager:UnRegSkillEndCallback()
    manager:UnRegSkillBeginMoveCallback()
    manager:UnRegSkillMoveStopCallback()
    manager:UnRegFootprintCallback()
    manager:UnRegStateStageCallback()
    manager:UnRegOnBeginMoveLuaCallBack()
    manager:UnRegOnStopMoveLuaCallBack()
end


return CoreCallbackManager