---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/12/1 11:26
---
local SkillType = SGEngine.Core.SkillDefines

local SkillFactory = {}

function SkillFactory.CreateSkill(type, isHero)
    if SkillType.k_SkillTypeDefault == type then
        return SkillBase.New()
    elseif SkillType.k_SkillTypeMove == type then
        if isHero then
            return SkillMove.New()
        else
            return SkillMove3rd.New()
        end
    elseif SkillType.k_SkillTypeMovePro == type then
        if isHero then
            return SkillMovePro.New()
        else
            return SkillMovePro3rd.New()
        end
    elseif SkillType.k_SkillTypeRootMotion == type then
        return SkillRootMotion.New()
    elseif SkillType.k_SkillTypeCharge == type then
        if isHero then
            return SkillCharge.New()
        else
            return SkillCharge3rd.New()
        end
    elseif SkillType.k_SkillTypeP2P == type then
        if isHero then
            return SkillP2P.New()
        else
            return SkillP2P3rd.New()
        end
    elseif SkillType.k_SkillTypeJump == type then
        return SkillJump.New()
    end
end

return SkillFactory