---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/7/30 10:50
---
local EffectBase = require("Engine/Systems/EffectSystem/Effects/EffectBase")
local AudioEffect = class("AudioEffect", EffectBase)
local EffectStatus = require("Engine/Systems/EffectSystem/EffectStatus")
function AudioEffect:Ctor(...)
    AudioEffect.__super.Ctor(self,...)
end

function AudioEffect:Start(needLoadResource)
	self.m_Status = EffectStatus.Started
	local model =  self.m_Owner:GetModel()
--	AudioManager:PlaySound(self.m_Config.m_Path,model)
end

function AudioEffect:Update(deltaTime)
    self.m_Time = self.m_Time + deltaTime
    local duration = self.m_Config.m_Duration
    if duration > 0 and self.m_Time > duration then
        self:Finish()
    end
end

function AudioEffect:Destroy()
	self.m_IsDestroy = true
end

function AudioEffect:Finish()
     self.m_Status = EffectStatus.Ended
end

function AudioEffect:IsFinish()
    return self.m_Status == EffectStatus.Ended
end

function AudioEffect:IsAvailable()
    return self.m_Status == EffectStatus.Ended
end
return AudioEffect