---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/7/30 10:50
---
local EffectBase = require("Engine/Systems/EffectSystem/Effects/EffectBase")
local PoolingStrategyTypeEnum = require("Engine/Systems/ResourceSystem/PoolingStrategyTypeEnum")
local PlaySpeedControlEffect = class("PlaySpeedControlEffect", EffectBase)

function PlaySpeedControlEffect:Ctor(...)
    self.m_NotInfluencedByPlaySpeed = true
    PlaySpeedControlEffect.__super.Ctor(self,...)
    self.m_PoolingStrategyType = PoolingStrategyTypeEnum.DontDestroyOnLoad
end

function PlaySpeedControlEffect:Start(needLoadResource)
    self.m_Owner.m_PlaySpeedControlActive = true
    self.__super.Start(self, needLoadResource)
end

function PlaySpeedControlEffect:OnLoadModelSuccess()
    local type = System.Type.GetType("SGEngine.Core.PlaySpeedEffect")
    self.m_PlaySpeedControlBehaviour = self.m_Instance:GetComponent(type)
    if self.m_PlaySpeedControlBehaviour ~= nil then
        self.m_PlaySpeedControlBehaviour:SetEndCallBack(function()
            self.m_Owner.m_PlaySpeedControlComponent:DetachOtherObjects()
        end)
        self.m_PlaySpeedControlBehaviour:SetSpeedCallBack(function(speed)
            self.m_Owner.m_PlaySpeedControlComponent:SetSpeed(speed, true)
        end)
        self.m_PlaySpeedControlBehaviour:Begin()
    end
end

function PlaySpeedControlEffect:Update(deltaTime)
    self.__super.Update(self, deltaTime)
end

function PlaySpeedControlEffect:Destroy()
    self.m_Owner.m_PlaySpeedControlActive = false
    self.m_PlaySpeedControlBehaviour:End()
    self.m_PlaySpeedControlBehaviour = nil
    self.__super.Destroy(self)
end

function PlaySpeedControlEffect:SetPlaySpeed(speed)
    ---override and do nothing
end

return PlaySpeedControlEffect