---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/7/30 10:50
---
local EffectBase = require("Engine/Systems/EffectSystem/Effects/EffectBase")
local ShakeCameraEffect = class("ShakeCameraEffect", EffectBase)

function ShakeCameraEffect:Ctor(...)
    ShakeCameraEffect.__super.Ctor(self,...)
end

function ShakeCameraEffect:Start(needLoadResource)
    self.m_Time = 0.0
    self.__super.Start(self, needLoadResource)
end

function ShakeCameraEffect:SetPlaySpeed(speed)
    ---override and do nothing
end

return ShakeCameraEffect