---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/7/30 10:50
---
local WaterRippleEffect = class("WaterRippleEffect")

function WaterRippleEffect:Ctor(...)
    self.go = UnityEngine.GameObject.New("WaterRipple")
    UnityEngine.GameObject.DontDestroyOnLoad(self.go)
    self.wre = self.go:AddComponent(System.Type.GetType("SGEngine.Core.WaterRippleEffect"))
end

function WaterRippleEffect:GetInstance()
    if self.instance == nil then
        self.instance = WaterRippleEffect.New()
    end

    if self.wre == nil then
        self.go = UnityEngine.GameObject.Find("WaterRipple")
        if self.go == nil then
            self.go = UnityEngine.GameObject.New("WaterRipple")
            UnityEngine.GameObject.DontDestroyOnLoad(self.go)
        end
        self.wre = self.go:AddComponent(System.Type.GetType("SGEngine.Core.WaterRippleEffect"))
    end

    return self.instance
end

function WaterRippleEffect:Play()
    if self.wre ~= nil then
        self.wre:Play()
    end
end


function WaterRippleEffect:Destroy()
    UnityEngine.GameObject.Destroy(self.go)
    self.wre = nil
    self.instance = nil
end


return WaterRippleEffect