---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/3/26 11:16
---

local SGMissileStage = require("Engine/Systems/ObjectSystem/SGMissile/SGMissileStage")
local SGMissileStageStay = class("SGMissileStageStay", SGMissileStage)

function SGMissileStageStay:Ctor(stageConfig, index)
    SGMissileStageStay.__super.Ctor(self, stageConfig, index)
end

function SGMissileStageStay:Start(missileObj, startPosition, startAngle)
    SGMissileStageStay.__super.Start(self, missileObj, startPosition, startAngle)
    self.m_StartAngle = startAngle
end

function SGMissileStageStay:Update()
    if not self.m_Owner then
        return
    end

    if self.m_RotateSpeed == 0 then
        return
    end

    local deltaAngle = self.m_StartAngle + Time.deltaTime * self.m_RotateSpeed
    local angle = self.m_Owner:GetAngle()
    self.m_Owner:SetAngle(deltaAngle + angle)
end

return SGMissileStageStay