---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/10/25 14:21
---
local SGCtrl = class("SGCtrl", SGObject)
SGCtrl.m_ObjectType = ObjectTypeEnum.Ctrl
function SGCtrl:Ctor()
    SGCtrl.__super.Ctor(self)
end

function SGCtrl:RegisterCommonComponents()
end

function SGCtrl:RegisterSerializedComponents()
end

function SGCtrl:Deserialize(netBuffer)
    local core = self.m_Core
    self.m_SceneId = netBuffer:ReadInt()
    --Logger.LogInfo("(SGCtrl)[Deserialize]m_SceneId:%s", tostring(self.m_SceneId))
    local position = Vector3.New()
    local angle
    position.x, position.y, position.z, angle = netBuffer:ReadPosAngle(position.x, position.y, position.z, angle)
    local modelId = netBuffer:ReadInt()
    --Logger.LogInfo("(SGCtrl)[Deserialize]modelId:%s", tostring(modelId))
    local scale = netBuffer:ReadFloat()
    --Logger.LogInfo("(SGCtrl)[Deserialize]scale:%s", tostring(scale))
    local objectId = netBuffer:ReadInt()
    --Logger.LogInfo("(SGCtrl)[Deserialize]objectId:%s, frame:%s", tostring(objectId), Time.frameCount)
    --Logger.LogInfo("(SGCtrl)[Deserialize]Position:%s, %s, %s, angle: %s", tostring(position.x), tostring(position.y), tostring(position.z), tostring(angle))
    --local color = UnityEngine.Color.blue
    --SGEngine.Core.DebugDraw.CreateGo(position, color, 1, "Deserialize", angle)

    self:SetObjectID(objectId)
    ObjectManager.AddObject(objectId, self)
    self:SetModelID(modelId)
    self:SetPosition(position)
    self:SetAngle(angle)
    self:SetScale(scale)
end

function SGCtrl:CheckSerialize(buffer, endFlag)
    local currentEnd = buffer:ReadUByte()
    if currentEnd ~= endFlag then
        Logger.Error("[SGCtrl](CheckSerialize) %X is wrong", endFlag)
        return false
    end
    return true
end

return SGCtrl

