---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/1/19 11:05
---
---@class SGMount : SGObject
local SGMount = class("SGMount", SGObject)
local StateConsts = require("Engine/Systems/ObjectSystem/State/StateConsts")
SGMount.m_ObjectType = ObjectTypeEnum.Mount
local StateDefine = SGEngine.Core.StateDefine

function SGMount:Ctor()
    SGMount.__super.Ctor(self)
end

function SGMount:SetModel(go, animationType)
    SGMount.__super.SetModel(self, go, animationType)
end

function SGMount:OnModelLoadComplete()
    SGMount.__super.OnModelLoadComplete(self)
end

function SGMount:OnLateUpdate()
    self.m_Core:OnLateUpdate()
end

function SGMount:SetRider(owner)
    local objectId = owner:GetObjectID()
    Logger.LogInfo("[SGMount](SetRider) SetRider:%s", objectId)
    self.m_Core:SetRider(objectId)
    if owner:IsState(StateDefine.k_StateMove) then
        self:PlayAnimation(StateConsts.k_RunAnimationName)
    else
        self:PlayAnimation(StateConsts.k_IdleAnimationName)
    end
    if owner:IsHero() then
        self:SetLayer("Hero")
    end
end

function SGMount:DoInit(needAttachGround)
    Logger.LogInfo("[SGMount](DoInit) DoInit")
    self.m_Core:DoInit(needAttachGround)
end

function SGMount:GetBodyPartTransform(name)
    return self.m_Core:GetBodyPartTransform(name)
end

return SGMount