---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/8/1 14:51
---
local StateConsts = require("Engine/Systems/ObjectSystem/State/StateConsts")
---@class StateFreeze:StateBase
local StateFreeze = class("StateFreeze", StateBase)
local StateDefine = SGEngine.Core.StateDefine
local AnimationEventDefines = SGEngine.Core.AnimationEventDefines
local HitTypeEnum = StateConsts.HitTypeEnum

function StateFreeze.Ctor(owner, stateComponent)
    StateFreeze.__super.Ctor(owner, stateComponent)
    stateComponent.m_StateFreezeParam = {}
end

function StateFreeze.Init(owner, stateComponent)
    --Logger.LogInfo("[StateFreeze](Init), frame:%s", Time.frameCount)
    StateFreeze.__super.Init(owner, stateComponent)
    owner:FreezeAnimator()
    owner:PlayIceFreeze(0)
end

function StateFreeze.Update(deltaTime, owner, stateComponent)
end

function StateFreeze.Destroy(owner, stateComponent)
    --Logger.LogInfo("[StateFreeze](Init), frame:%s", Time.frameCount)
    StateFreeze.__super.Destroy(owner, stateComponent)
    owner:UnFreezeAnimator()
    owner:PlayIceFreeze(1)
end

function StateFreeze.SetParamToCore(owner, targetPosX, targetPosY, targetPosZ, speed)
    owner.m_Core:OnSyncState(StateDefine.k_StateFreeze, targetPosX, targetPosY, targetPosZ, speed)
end

return StateFreeze