---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/12/1 10:31
---
---@class StateBase
local StateBase = class("StateBase")

function StateBase.Ctor(owner, stateComponent)
end

--在C#的State.Init之后
function StateBase.Init(owner, stateComponent)
end

--在C#的State.Destroy之后
function StateBase.Destroy(owner, stateComponent)
end

function StateBase.Update(deltaTime, owner, stateComponent)
end

function StateBase.LateUpdate(owner, stateComponent)
end

function StateBase.SetParam(...)
end

function StateBase.OnBeginMove(owner, stateComponent)
end

function StateBase.OnStopMove(owner, stateComponent)
end

function StateBase.OnModelLoadComplete(owner, stateComponent)
end

function StateBase.OnSkillButtonUp(owner, stateComponent)
end

function StateBase.OnSkillButtonDown(owner, stateComponent, angle)
end

function StateBase.OnSkillButtonMove(owner, stateComponent, angle)
end

function StateBase.RegisterDispatchEvent(owner)
end

function StateBase.UnRegisterDispatchEvent(owner)
end

function StateBase.PlayAnimation(owner, animationName, crossFade, callback)
    if owner == nil then
        return
    end
    crossFade = crossFade or 0.1
    owner:PlayAnimation(animationName, 0, crossFade, 0, callback)
end

return StateBase