---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/1/26 17:39
---
local StateDefine = SGEngine.Core.StateDefine
local StateConsts = require("Engine/Systems/ObjectSystem/State/StateConsts")
local BattleMessage = require("MainGame/Message/BattleMessage")
local StateCinema = class("StateCinema", StateBase)
local AnimationEventDefines = SGEngine.Core.AnimationEventDefines

function StateCinema.Ctor(owner, stateComponent)
    StateCinema.__super.Ctor(owner, stateComponent)
    stateComponent.m_StateCinemaParam = {}
end

function StateCinema.Init(owner, stateComponent)
    StateCinema.__super.Init(owner, stateComponent)
    stateComponent.m_StateCinemaParam.m_IsDefaultAnim = false
    if stateComponent.m_StateCinemaParam.m_CinemaAnim == nil then
       stateComponent.m_StateCinemaParam.m_CinemaAnim = StateConsts.k_IdleAnimationName
       stateComponent.m_StateCinemaParam.m_IsDefaultAnim = true
    end
    StateCinema.PlayAnimation(owner, stateComponent.m_StateCinemaParam.m_CinemaAnim, 0.1, function(eventName)
        StateCinema.OnCinemaAnimCallBack(owner, eventName, stateComponent.m_StateCinemaParam.m_IsDefaultAnim)
    end)
end

function StateCinema.OnCinemaAnimCallBack(owner, eventName, isDefaultAnim)
    if eventName == AnimationEventDefines.k_EventEnd and not isDefaultAnim then
       StateCinema.PlayAnimation(owner, StateConsts.k_IdleAnimationName, 0.3)       
    end
end

function StateCinema.Destroy(owner, stateComponent)
    stateComponent.m_StateCinemaParam.m_CinemaAnim = nil
end

return StateCinema