---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/12/27 18:18
---
local StateConsts = require("Engine/Systems/ObjectSystem/State/StateConsts")
local StateDaze = class("StateDaze", StateBase)
local StateDefine = SGEngine.Core.StateDefine

function StateDaze.Ctor(owner, stateComponent)
    StateDaze.__super.Ctor(owner, stateComponent)
end

function StateDaze.Init(owner, stateComponent)
    StateDaze.__super.Init(owner, stateComponent)
    StateDaze.PlayAnimation(owner, StateConsts.k_Daze)
end

function StateDaze.Destroy(owner, stateComponent)
    StateDaze.__super.Destroy(owner, stateComponent)
end

return StateDaze