---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/12/15 21:42
---
local ComponentDefine = require("Engine/Systems/ObjectSystem/Components/ComponentDefine")
local FightResultBase = require("MainGame/Game/Logic/Skill/FightResult/FightResultBase")
local ObjectPool = require("MainGame/Game/Logic/Skill/ObjectPool")
local FightResultDead = class("FightResultDead", FightResultBase)
local FightResultType = ComponentDefine.FightResultType
local StateDefine = SGEngine.Core.StateDefine

FightResultDead.m_FightResultType = FightResultType.k_Dead
if FightResultDead.m_Pool == nil then
    FightResultDead.m_Pool = ObjectPool.CreatePool(FightResultDead)
end

function FightResultDead.Ctor()
    FightResultDead.__super.Ctor(self)
end

function FightResultDead.Get()
    local pool = FightResultDead.m_Pool
    if pool then
        return pool:Get()
    end
end

function FightResultDead:Recycle()
    local pool = FightResultDead.m_Pool
    if pool then
        pool:Recycle(self, true)
    end
end

function FightResultDead:Init(attackObjectId)
    FightResultDead.__super.Init(self)
    self.m_AttackObjectId = attackObjectId
end

function FightResultDead:Deserialize(netBuffer)
    self.m_TargetID = netBuffer:ReadUInt()
    self.m_DeadType = netBuffer:ReadUByte()
    self.m_PosX, self.m_PosY, self.m_PosZ, self.m_Angle = netBuffer:ReadPosAngle(nil, nil, nil, nil)
    self.m_HitPoint = netBuffer:ReadUByte()
    --Logger.LogInfo("[FightResultDead](Execute), [%s] obj will dead by obj:[%s]", self.m_TargetID, self.m_AttackObjectId)
end

function FightResultDead:Execute()
    --Logger.LogInfo("[FightResultDead](Execute), [%s] obj dead by [%s]", self.m_TargetID, self.m_AttackObjectId)
    local object = ObjectManager.GetObject(self.m_TargetID)
    if object == nil then
        return
    end

    if object:IsValid() == false then
        return
    end
    object:ChangeToDead(self.m_PosX, self.m_PosY, self.m_PosZ, self.m_Angle, false)
end

return FightResultDead