---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/3/22 15:09
---

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/12/27 17:52
---
local ComponentDefine = require("Engine/Systems/ObjectSystem/Components/ComponentDefine")
local FightResultBase = require("MainGame/Game/Logic/Skill/FightResult/FightResultBase")
local ObjectPool = require("MainGame/Game/Logic/Skill/ObjectPool")
local FightResultMissile = class("FightResultMissile", FightResultBase)
local FightResultType = ComponentDefine.FightResultType

FightResultMissile.m_FightResultType = FightResultType.k_Damage
if FightResultMissile.m_Pool == nil then
    FightResultMissile.m_Pool = ObjectPool.CreatePool(FightResultMissile)
end

function FightResultMissile.Ctor()
    FightResultMissile.__super.Ctor(self)
end

function FightResultMissile.Get()
    local pool = FightResultMissile.m_Pool
    if pool then
        return pool:Get()
    end
end

function FightResultMissile:Recycle()
    local pool = FightResultMissile.m_Pool
    if pool then
        pool:Recycle(self, true)
    end
end

function FightResultMissile:Init(missileObjectID)
    FightResultMissile.__super.Init(self)
    self.m_MissileObjectID = missileObjectID
end

function FightResultMissile:Deserialize(netBuffer)
    self.m_HitPoint = netBuffer:ReadUByte()
    --Logger.LogInfo("[FightResultMissile]Deserialize FightResultMissile:m_MissileCtrlId:{%d},m_HitPoint:{%d}", self.m_MissileObjectID, self.m_HitPoint)
end

function FightResultMissile:Execute()
    local object = ObjectManager.GetObject(self.m_MissileObjectID)
    if not object then
        return
    end

    if object:IsValid() == false then
        return
    end
    object:Start()
end

return FightResultMissile