---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/12/31 14:56
---
local TouchButton = require("Engine/UI/Base/TouchButton")
local SkillConfigData = require("MainGame/ConfigData/SkillConfigData")
local SkillType = SGEngine.Core.SkillDefines
local DOTweenModuleUI = DG.Tweening.DOTweenModuleUI
local SkillButton = class("SkillButton", TouchButton)

function SkillButton:Ctor(transform)
    SkillButton.__super.Ctor(self, transform)
end

function SkillButton:RefreshData(skillId, buttonType)
    local config = SkillConfigData:Get(skillId)
    if not config then
        return
    end

    if self:NeedDragUI(config) then
        self:SetDragEnable(true)
    else
        self:SetDragEnable(false)
    end
    self.m_SkillId = skillId
    self.m_Config = config
    self:SetButtonType(buttonType)
end

function SkillButton:NeedDragUI(config)
    if config.SkillModule == SkillType.k_SkillTypeMovePro then
        return true
    elseif config.SkillModule == SkillType.k_SkillTypeMove then
        return config.SkillModuleParams[1] == 1
    end
end

function SkillButton:RefreshCD(skillId)
    local skillImage = self.CD
    if skillId ~= self.m_SkillId then
        return
    end

    if skillImage then
        skillImage.fillAmount = 1
        DOTweenModuleUI.DOFillAmount(skillImage, 0, self.m_Config.CoolDown)
    end
end

function SkillButton:OnClickDown()
    SkillButton.__super.OnClickDown(self)
    if self.m_SkillId then
         ObjectManager.m_Hero:UseSkill(self.m_SkillId)
        --ObjectManager.m_Hero.m_SkillTargetComponent:ChaseTargetAndPlaySkill(self.m_SkillId)
    end
    local hero = ObjectManager.m_Hero
    if hero then
        hero:OnSkillButtonDown(self.m_SkillAngle)
    end
end

function SkillButton:OnDrag(angle)
    SkillButton.__super.OnDrag(self, angle)
    self.m_SkillAngle = angle
    local hero = ObjectManager.m_Hero
    if hero then
        hero:OnSkillButtonMove(self.m_SkillAngle)
    end
end

function SkillButton:OnClickUp()
    SkillButton.__super.OnClickUp(self)
    self.m_SkillAngle = nil
    local hero = ObjectManager.m_Hero
    if hero then
        hero:OnSkillButtonUp()
    end
end

return SkillButton