---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/7/24 10:37
---
---@class CacheEvent
local class = require("Engine/Common/Base/Class")
local CacheEvent = class("CacheEvent")

function CacheEvent:Ctor(instance, call, ...)
    self.m_Instance = instance
    self.m_Function = call
    self.m_Param = { ... }
end

function CacheEvent:Invoke()
    if self.m_Function ~= nil then
        self.m_Instance[self.m_Function](self.m_Instance, table.unpack(self.m_Param))
    end
end

return CacheEvent