---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/7/23 20:59
---
---
local StringUtil = require("Engine/Common/Utilities/StringUtil")
local EffectPosType = require("Engine/Systems/EffectSystem/EffectPosType")

---@class EffectConfig
local EffectConfig = {}
EffectConfig.m_DataMap = {}
function EffectConfig.Get(id)
    local data = EffectConfig.m_DataMap[id]
    if data then
        return data
    end

    local config = AllEffectConfig[id]
    if not config then
        Logger.LogErrorFormat("Get effect config faild, id:{0}", id)
        return nil
    end
    local result = {}
    ---@type int
    result.m_Id = config.Id

    result.m_Type = config.Type
    ---@type string
    result.m_Path = config.Path
    ---@type EffectPosType
    result.m_PosType = config.PosType
    ---@type string
    result.m_BindPath = config.BindPath

    if config.PosType ~= EffectPosType.None then
        ---@type UnityEngine.Vector3
        result.m_PositionOffset = StringUtil.String2Vector3(config.PositionOffset, ",")
        ---@type UnityEngine.Vector3
        result.m_RotationOffset = StringUtil.String2Vector3(config.RotationOffset, ",")
        ---@type UnityEngine.Vector3
        result.m_Scale = StringUtil.String2Vector3(config.Scale, ",")
    end

    ---@type float
    result.m_Duration = config.Duration
    EffectConfig.m_DataMap[id] = result
    return result
end


return EffectConfig