---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/7/30 11:16
---

local EffectConst = require("Engine/Systems/EffectSystem/EffectConst")
local EffectBase = require("Engine/Systems/EffectSystem/Effects/EffectBase")
local PlaySpeedControlEffect = require("Engine/Systems/EffectSystem/Effects/PlaySpeedControlEffect")
local ShakeCameraEffect = require("Engine/Systems/EffectSystem/Effects/ShakeCameraEffect")
local GlobalLuminanceEffect = require("Engine/Systems/EffectSystem/Effects/GlobalLuminanceEffect")
local RadialBlurEffect = require("Engine/Systems/EffectSystem/Effects/RadialBlurEffect")
local DestroyGrassEffect = require("Engine/Systems/EffectSystem/Effects/DestroyGrassEffect")
local GhostEffect = require("Engine/Systems/EffectSystem/Effects/GhostEffect")
local AudioEffect = require("Engine/Systems/EffectSystem/Effects/AudioEffect")
local FootprintEffect = require("Engine/Systems/EffectSystem/Effects/FootprintEffect")
local FootDustEffect = require("Engine/Systems/EffectSystem/Effects/FootDustEffect")
local MotionEffect = require("Engine/Systems/EffectSystem/Effects/MotionEffect")
local WaterWaveEffect = require("Engine/Systems/EffectSystem/Effects/WaterWaveEffect")
local ChainAttackEffect = require("Engine/Systems/EffectSystem/Effects/ChainAttackEffect")
local EffectTypeDefine = EffectConst.EffectTypeDefine
local EffectFactory = {}
local CreateFuncMap = {}

CreateFuncMap[EffectTypeDefine.k_ShakeCamera] = ShakeCameraEffect.New
CreateFuncMap[EffectTypeDefine.k_PlaySpeedControl] = PlaySpeedControlEffect.New
CreateFuncMap[EffectTypeDefine.k_CommonEffect] = EffectBase.New
CreateFuncMap[EffectTypeDefine.k_GlobalLuminance] = GlobalLuminanceEffect.New
CreateFuncMap[EffectTypeDefine.k_DestroyGrass] = DestroyGrassEffect.New
CreateFuncMap[EffectTypeDefine.k_Ghost] = GhostEffect.New
CreateFuncMap[EffectTypeDefine.k_Audio] = AudioEffect.New
CreateFuncMap[EffectTypeDefine.k_RadialBlurEffect] = RadialBlurEffect.New
CreateFuncMap[EffectTypeDefine.k_MotionEffect] = MotionEffect.New
CreateFuncMap[EffectTypeDefine.k_WaterWave] = WaterWaveEffect.New
CreateFuncMap[EffectTypeDefine.k_FootprintEffect] = FootprintEffect.New
CreateFuncMap[EffectTypeDefine.k_FootDustEffect] = FootDustEffect.New
CreateFuncMap[EffectTypeDefine.k_ChainAttackEffect] = ChainAttackEffect.New

function EffectFactory.Create(effectId, type, objOwner)
    local createFunc = CreateFuncMap[type]
    if createFunc then
        return createFunc(effectId, objOwner)
    end
    return nil
end

return EffectFactory