---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/7/23 21:01
---
local EffectConst = {
    EffectTypeDefine = {
        k_CommonEffect = 1,
        k_ShakeCamera = 2,
        k_PlaySpeedControl = 3,
        k_GlobalLuminance = 4,
        k_DestroyGrass = 5,
        k_Ghost = 6,
        k_RadialBlurEffect = 7,
        k_Audio = 10,
        k_MotionEffect = 11,
        k_WaterWave = 12,
        k_ChainAttackEffect = 13,
        k_FootprintEffect = 100,
        k_FootDustEffect = 101,
    }
}
return EffectConst