---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/7/23 21:14
---

---@class EffectStatus
--enum
local T = {}
T.UnInit = -1
T.Started = 0
T.Ended = 1
return T