---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/9/16 14:12
---

local GeometryUtil = {}

function GeometryUtil.IsPointInRect(p, a, b, c, d)
    local cross = function(m, n)
        return m.x * n.y - n.y * m.x
    end

    local minus = function(m, n)
        return {x = m.x - n.x, y = m.y - n.y}
    end

    local ab = minus(a, b)
    local ap = minus(a, p)
    local cd = minus(c, d)
    local cp = minus(c, p)
    local da = minus(d, a)
    local dp = minus(d, p)
    local bc = minus(b, c)
    local bp = minus(b, p)

    local isBetweenAB_CD = (cross(ab, ap) * cross(cd, cp)) > 0
    local isBetweenDA_BC = (cross(da, dp) * cross(bc, bp)) > 0
    return isBetweenAB_CD and isBetweenDA_BC
end



return GeometryUtil