---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/6/29 15:57
---

GameLoop = GameLoop or {}
local Time = Time
function GameLoop.Init()
    AccountManager.Init()

    NetManager.Init()
    SceneManager.Init()
    TimeLineManager.Init()
    CinemaManager.Init()

    UIManager.Init()
    ObjectManager.Init()
    ProcedureManager.Init()
    TurnStrategyManager.Init()
    CoreCallbackManager.Init()
    BfClientManager.Init()
end

function GameLoop.Update(deltaTime, unscaledDeltaTime)
    NetManager.Update()
    Time:SetDeltaTime(deltaTime, unscaledDeltaTime)
    ObjectManager.Update(deltaTime)
    EffectManager.Update(deltaTime)
    UIManager.Update(deltaTime)
    ProcedureManager.Update()
    TurnStrategyManager.Update(deltaTime)
    TimeLineManager.Update(deltaTime)
    if UNITY_EDITOR then
        ReloadManager.Update(deltaTime)
    end
end

function GameLoop.LateUpdate()
    ObjectManager.LateUpdate()
    Time:SetFrameCount()
end

---not called for now
function GameLoop.FixedUpdate(fixedDeltaTime)
    Time:SetFixedDelta(fixedDeltaTime)
end

function GameLoop.Restart()
    ObjectManager.Restart()
    CinemaManager.Restart()
end

function GameLoop.Destroy()
    CoreCallbackManager.Destroy()
    NetManager.Destroy()
    TimeLineManager.Destroy()
    CinemaManager.Destroy()
    UIManager.Destroy()
    ObjectManager.Destroy()
    SceneManager.Destroy()
    ProcedureManager.Destroy()
    TurnStrategyManager.Destroy()
    BfClientManager.Destroy()
end

function GameLoop.BeforeChangeScene(prevSceneType, nextSceneType)
    CinemaManager.BeforeChangeScene(prevSceneType, nextSceneType)
    TimeLineManager.BeforeChangeScene(prevSceneType, nextSceneType)
    UIManager.BeforeChangeScene(prevSceneType, nextSceneType)
    ObjectManager.BeforeChangeScene(prevSceneType, nextSceneType)
    EffectManager.BeforeChangeScene(prevSceneType, nextSceneType)
    SceneManager.BeforeChangeScene(prevSceneType, nextSceneType)
    ProcedureManager.BeforeChangeScene(prevSceneType, nextSceneType)
    TurnStrategyManager.BeforeChangeScene(prevSceneType, nextSceneType)
    OutlineManager.BeforeChangeScene(prevSceneType, nextSceneType)
end

function GameLoop.AfterChangeScene(prevSceneType, nextSceneType)
    CinemaManager.AfterChangeScene(prevSceneType, nextSceneType)
    UIManager.AfterChangeScene(prevSceneType, nextSceneType)
    ObjectManager.AfterChangeScene(prevSceneType, nextSceneType)
    EffectManager.AfterChangeScene(prevSceneType, nextSceneType)
    SceneManager.AfterChangeScene(prevSceneType, nextSceneType)
    ProcedureManager.AfterChangeScene(prevSceneType, nextSceneType)
    TurnStrategyManager.AfterChangeScene(prevSceneType, nextSceneType)
    TimeLineManager.AfterChangeScene(prevSceneType, nextSceneType)
    OutlineManager.AfterChangeScene(prevSceneType, nextSceneType)
end

function GameLoop.GetLuaMem()
    local mem = collectgarbage("count")
    return math.ceil(mem)
end

return GameLoop