---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/3/9 16:59
---
---
local TurnStrategyView = class('TurnStrategyView', BaseView)

--子类重写
function TurnStrategyView:InitUI()
    self:AddButtonListener(self.startButton, function ()
        self.startButton.gameObject:SetActive(false)
        TurnStrategyManager.CreateDemo()
    end)
end

function TurnStrategyView:OnOpen()
end

function TurnStrategyView:OnClose()
end

return TurnStrategyView
